set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[1].Inverter0/LUT6_inst}]
set_property LOC SLICE_X37Y125 [get_cells {design_1_i/BTI_RO1/inst/CRO[1].Inverter0/LUT6_inst}]
set_property BEL C6LUT [get_cells design_1_i/BTI_RO1/inst/w_inst__7]
set_property LOC SLICE_X37Y125 [get_cells design_1_i/BTI_RO1/inst/w_inst__7]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[1].Inverter2/LUT6_inst}]
set_property LOC SLICE_X37Y125 [get_cells {design_1_i/BTI_RO1/inst/CRO[1].Inverter2/LUT6_inst}]
set_property BEL D6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[1].Inverter1/LUT6_inst}]
set_property LOC SLICE_X37Y125 [get_cells {design_1_i/BTI_RO1/inst/CRO[1].Inverter1/LUT6_inst}]
