# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FromArash/heater.XDC

# XDC: imports/FromArash/BTI_RO1.XDC

# XDC: imports/FromArash/BTI_RO2.XDC

# XDC: imports/new/constraints_5x3_ROs.xdc

# XDC: new/HCI.xdc

# XDC: new/Fixing.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4_heater_0_0/design_1_AXI4_heater_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI4_heater_0_0 || ORIG_REF_NAME==design_1_AXI4_heater_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_BTI_RO1_0_1/design_1_AXI_3stage_BTI_RO1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_BTI_RO1_0_1 || ORIG_REF_NAME==design_1_AXI_3stage_BTI_RO1_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_BTI_RO2_0_3/design_1_AXI_3stage_BTI_RO2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_BTI_RO2_0_3 || ORIG_REF_NAME==design_1_AXI_3stage_BTI_RO2_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LowFreq100Hz_ClkGen_0_0/design_1_LowFreq100Hz_ClkGen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_LowFreq100Hz_ClkGen_0_0 || ORIG_REF_NAME==design_1_LowFreq100Hz_ClkGen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_HCI_0_1/design_1_AXI_3stage_HCI_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_HCI_0_1 || ORIG_REF_NAME==design_1_AXI_3stage_HCI_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_HCI_0_2/design_1_AXI_3stage_HCI_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_HCI_0_2 || ORIG_REF_NAME==design_1_AXI_3stage_HCI_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_HCI_0_3/design_1_AXI_3stage_HCI_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_HCI_0_3 || ORIG_REF_NAME==design_1_AXI_3stage_HCI_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_2 || ORIG_REF_NAME==design_1_clk_wiz_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_HCI_2_0/design_1_AXI_3stage_HCI_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_HCI_2_0 || ORIG_REF_NAME==design_1_AXI_3stage_HCI_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_HCI_3_0/design_1_AXI_3stage_HCI_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_HCI_3_0 || ORIG_REF_NAME==design_1_AXI_3stage_HCI_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_HCI_4_0/design_1_AXI_3stage_HCI_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_HCI_4_0 || ORIG_REF_NAME==design_1_AXI_3stage_HCI_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_3stage_HCI_5_0/design_1_AXI_3stage_HCI_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_3stage_HCI_5_0 || ORIG_REF_NAME==design_1_AXI_3stage_HCI_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_RO2_0_0/design_1_AXI_RO2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_RO2_0_0 || ORIG_REF_NAME==design_1_AXI_RO2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_RO2_0_1/design_1_AXI_RO2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_RO2_0_1 || ORIG_REF_NAME==design_1_AXI_RO2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_RO2_0_2/design_1_AXI_RO2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_RO2_0_2 || ORIG_REF_NAME==design_1_AXI_RO2_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_RO2_0_3/design_1_AXI_RO2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_RO2_0_3 || ORIG_REF_NAME==design_1_AXI_RO2_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_RO2_0_4/design_1_AXI_RO2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_RO2_0_4 || ORIG_REF_NAME==design_1_AXI_RO2_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_RO2_0_5/design_1_AXI_RO2_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_RO2_0_5 || ORIG_REF_NAME==design_1_AXI_RO2_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_div_0_0/design_1_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_div_0_0 || ORIG_REF_NAME==design_1_clk_div_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_1/design_1_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
