#HCI_0
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[6].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[7].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[8].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[9].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[10].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[11].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[12].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[13].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[14].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[15].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[16].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[17].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[18].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_0/inst/RO[19].notGate[0].Inverter/out_sig}]


#HCI_1
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[6].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[7].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[8].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[9].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[10].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[11].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[12].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[13].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[14].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[15].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[16].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[17].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[18].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_1/inst/RO[19].notGate[0].Inverter/out_sig}]


#HCI_2
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[6].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[7].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[8].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[9].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[10].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[11].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[12].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[13].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[14].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[15].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[16].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[17].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[18].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_2/inst/RO[19].notGate[0].Inverter/out_sig}]


#HCI_3
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[6].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[7].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[8].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[9].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[10].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[11].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[12].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[13].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[14].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[15].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[16].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[17].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[18].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_3/inst/RO[19].notGate[0].Inverter/out_sig}]


#HCI_4
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[6].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[7].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[8].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[9].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[10].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[11].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[12].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[13].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[14].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[15].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[16].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[17].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[18].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_4/inst/RO[19].notGate[0].Inverter/out_sig}]


#HCI_5
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[6].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[7].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[8].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[9].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[10].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[11].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[12].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[13].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[14].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[15].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[16].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[17].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[18].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_5/inst/RO[19].notGate[0].Inverter/out_sig}]


#HCI_6
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[6].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[7].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[8].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[9].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[10].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[11].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[12].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[13].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[14].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[15].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[16].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[17].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[18].notGate[0].Inverter/out_sig}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/HCI_6/inst/RO[19].notGate[0].Inverter/out_sig}]







