set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[19].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[19].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[18].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[18].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[17].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[17].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[16].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[16].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[15].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[15].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[14].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[14].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[13].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[13].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[12].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[12].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[11].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[11].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[10].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[10].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[9].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[9].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[8].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[8].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[7].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[7].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[6].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[6].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[5].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[5].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[4].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[4].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[3].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[3].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[2].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[2].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[1].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[1].Inverter0}]
set_property BEL B6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[0].Inverter1}]
set_property BEL A6LUT [get_cells {design_1_i/BTI_RO1/inst/CRO[0].Inverter0}]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[0].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[1].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[2].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[3].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[4].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[5].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[6].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[7].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[8].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[9].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[10].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[11].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[12].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[13].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[14].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[15].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[16].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[17].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[18].Inverter0/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI_RO1/inst/CRO[19].Inverter0/in0[0]}]













